// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Framework.proto

package jmf.proto;

public final class FrameworkProto {
  private FrameworkProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SenderIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zmf.proto.SenderId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 typeId = 1;</code>
     */
    boolean hasTypeId();
    /**
     * <code>required uint32 typeId = 1;</code>
     */
    int getTypeId();

    /**
     * <code>required uint64 instanceId = 2;</code>
     */
    boolean hasInstanceId();
    /**
     * <code>required uint64 instanceId = 2;</code>
     */
    long getInstanceId();
  }
  /**
   * Protobuf type {@code zmf.proto.SenderId}
   */
  public static final class SenderId extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zmf.proto.SenderId)
      SenderIdOrBuilder {
    // Use SenderId.newBuilder() to construct.
    private SenderId(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private SenderId(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final SenderId defaultInstance;
    public static SenderId getDefaultInstance() {
      return defaultInstance;
    }

    public SenderId getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private SenderId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              typeId_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              instanceId_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jmf.proto.FrameworkProto.internal_static_zmf_proto_SenderId_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jmf.proto.FrameworkProto.internal_static_zmf_proto_SenderId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jmf.proto.FrameworkProto.SenderId.class, jmf.proto.FrameworkProto.SenderId.Builder.class);
    }

    public static com.google.protobuf.Parser<SenderId> PARSER =
        new com.google.protobuf.AbstractParser<SenderId>() {
      public SenderId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SenderId(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<SenderId> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int TYPEID_FIELD_NUMBER = 1;
    private int typeId_;
    /**
     * <code>required uint32 typeId = 1;</code>
     */
    public boolean hasTypeId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 typeId = 1;</code>
     */
    public int getTypeId() {
      return typeId_;
    }

    public static final int INSTANCEID_FIELD_NUMBER = 2;
    private long instanceId_;
    /**
     * <code>required uint64 instanceId = 2;</code>
     */
    public boolean hasInstanceId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint64 instanceId = 2;</code>
     */
    public long getInstanceId() {
      return instanceId_;
    }

    private void initFields() {
      typeId_ = 0;
      instanceId_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTypeId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasInstanceId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt64(2, instanceId_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, typeId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, instanceId_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.SenderId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jmf.proto.FrameworkProto.SenderId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jmf.proto.FrameworkProto.SenderId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jmf.proto.FrameworkProto.SenderId prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zmf.proto.SenderId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zmf.proto.SenderId)
        jmf.proto.FrameworkProto.SenderIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_SenderId_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_SenderId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jmf.proto.FrameworkProto.SenderId.class, jmf.proto.FrameworkProto.SenderId.Builder.class);
      }

      // Construct using jmf.proto.FrameworkProto.SenderId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        typeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        instanceId_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_SenderId_descriptor;
      }

      public jmf.proto.FrameworkProto.SenderId getDefaultInstanceForType() {
        return jmf.proto.FrameworkProto.SenderId.getDefaultInstance();
      }

      public jmf.proto.FrameworkProto.SenderId build() {
        jmf.proto.FrameworkProto.SenderId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jmf.proto.FrameworkProto.SenderId buildPartial() {
        jmf.proto.FrameworkProto.SenderId result = new jmf.proto.FrameworkProto.SenderId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.typeId_ = typeId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.instanceId_ = instanceId_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jmf.proto.FrameworkProto.SenderId) {
          return mergeFrom((jmf.proto.FrameworkProto.SenderId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jmf.proto.FrameworkProto.SenderId other) {
        if (other == jmf.proto.FrameworkProto.SenderId.getDefaultInstance()) return this;
        if (other.hasTypeId()) {
          setTypeId(other.getTypeId());
        }
        if (other.hasInstanceId()) {
          setInstanceId(other.getInstanceId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTypeId()) {
          
          return false;
        }
        if (!hasInstanceId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jmf.proto.FrameworkProto.SenderId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jmf.proto.FrameworkProto.SenderId) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int typeId_ ;
      /**
       * <code>required uint32 typeId = 1;</code>
       */
      public boolean hasTypeId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 typeId = 1;</code>
       */
      public int getTypeId() {
        return typeId_;
      }
      /**
       * <code>required uint32 typeId = 1;</code>
       */
      public Builder setTypeId(int value) {
        bitField0_ |= 0x00000001;
        typeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 typeId = 1;</code>
       */
      public Builder clearTypeId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        typeId_ = 0;
        onChanged();
        return this;
      }

      private long instanceId_ ;
      /**
       * <code>required uint64 instanceId = 2;</code>
       */
      public boolean hasInstanceId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint64 instanceId = 2;</code>
       */
      public long getInstanceId() {
        return instanceId_;
      }
      /**
       * <code>required uint64 instanceId = 2;</code>
       */
      public Builder setInstanceId(long value) {
        bitField0_ |= 0x00000002;
        instanceId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 instanceId = 2;</code>
       */
      public Builder clearInstanceId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        instanceId_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:zmf.proto.SenderId)
    }

    static {
      defaultInstance = new SenderId(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zmf.proto.SenderId)
  }

  public interface StateBroadcastOrBuilder extends
      // @@protoc_insertion_point(interface_extends:zmf.proto.StateBroadcast)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 zmqPubPort = 1;</code>
     */
    boolean hasZmqPubPort();
    /**
     * <code>required uint32 zmqPubPort = 1;</code>
     */
    int getZmqPubPort();

    /**
     * <code>required uint32 zmqRepPort = 2;</code>
     */
    boolean hasZmqRepPort();
    /**
     * <code>required uint32 zmqRepPort = 2;</code>
     */
    int getZmqRepPort();

    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    boolean hasSenderId();
    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    jmf.proto.FrameworkProto.SenderId getSenderId();
    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    jmf.proto.FrameworkProto.SenderIdOrBuilder getSenderIdOrBuilder();

    /**
     * <code>required string senderName = 4;</code>
     */
    boolean hasSenderName();
    /**
     * <code>required string senderName = 4;</code>
     */
    java.lang.String getSenderName();
    /**
     * <code>required string senderName = 4;</code>
     */
    com.google.protobuf.ByteString
        getSenderNameBytes();

    /**
     * <code>required uint32 version = 5;</code>
     */
    boolean hasVersion();
    /**
     * <code>required uint32 version = 5;</code>
     */
    int getVersion();

    /**
     * <code>required uint32 lifecycleState = 6;</code>
     */
    boolean hasLifecycleState();
    /**
     * <code>required uint32 lifecycleState = 6;</code>
     */
    int getLifecycleState();

    /**
     * <code>optional uint32 additionalLifecycleInfos = 7;</code>
     */
    boolean hasAdditionalLifecycleInfos();
    /**
     * <code>optional uint32 additionalLifecycleInfos = 7;</code>
     */
    int getAdditionalLifecycleInfos();

    /**
     * <code>optional bytes additionalStateInfos = 8;</code>
     */
    boolean hasAdditionalStateInfos();
    /**
     * <code>optional bytes additionalStateInfos = 8;</code>
     */
    com.google.protobuf.ByteString getAdditionalStateInfos();

    /**
     * <code>required uint32 multicastIdentifier = 9;</code>
     */
    boolean hasMulticastIdentifier();
    /**
     * <code>required uint32 multicastIdentifier = 9;</code>
     */
    int getMulticastIdentifier();
  }
  /**
   * Protobuf type {@code zmf.proto.StateBroadcast}
   */
  public static final class StateBroadcast extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:zmf.proto.StateBroadcast)
      StateBroadcastOrBuilder {
    // Use StateBroadcast.newBuilder() to construct.
    private StateBroadcast(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private StateBroadcast(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final StateBroadcast defaultInstance;
    public static StateBroadcast getDefaultInstance() {
      return defaultInstance;
    }

    public StateBroadcast getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private StateBroadcast(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              zmqPubPort_ = input.readUInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              zmqRepPort_ = input.readUInt32();
              break;
            }
            case 26: {
              jmf.proto.FrameworkProto.SenderId.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = senderId_.toBuilder();
              }
              senderId_ = input.readMessage(jmf.proto.FrameworkProto.SenderId.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(senderId_);
                senderId_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              senderName_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              version_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              lifecycleState_ = input.readUInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              additionalLifecycleInfos_ = input.readUInt32();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000080;
              additionalStateInfos_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000100;
              multicastIdentifier_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return jmf.proto.FrameworkProto.internal_static_zmf_proto_StateBroadcast_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return jmf.proto.FrameworkProto.internal_static_zmf_proto_StateBroadcast_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              jmf.proto.FrameworkProto.StateBroadcast.class, jmf.proto.FrameworkProto.StateBroadcast.Builder.class);
    }

    public static com.google.protobuf.Parser<StateBroadcast> PARSER =
        new com.google.protobuf.AbstractParser<StateBroadcast>() {
      public StateBroadcast parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StateBroadcast(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<StateBroadcast> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ZMQPUBPORT_FIELD_NUMBER = 1;
    private int zmqPubPort_;
    /**
     * <code>required uint32 zmqPubPort = 1;</code>
     */
    public boolean hasZmqPubPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 zmqPubPort = 1;</code>
     */
    public int getZmqPubPort() {
      return zmqPubPort_;
    }

    public static final int ZMQREPPORT_FIELD_NUMBER = 2;
    private int zmqRepPort_;
    /**
     * <code>required uint32 zmqRepPort = 2;</code>
     */
    public boolean hasZmqRepPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 zmqRepPort = 2;</code>
     */
    public int getZmqRepPort() {
      return zmqRepPort_;
    }

    public static final int SENDERID_FIELD_NUMBER = 3;
    private jmf.proto.FrameworkProto.SenderId senderId_;
    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    public boolean hasSenderId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    public jmf.proto.FrameworkProto.SenderId getSenderId() {
      return senderId_;
    }
    /**
     * <code>required .zmf.proto.SenderId senderId = 3;</code>
     */
    public jmf.proto.FrameworkProto.SenderIdOrBuilder getSenderIdOrBuilder() {
      return senderId_;
    }

    public static final int SENDERNAME_FIELD_NUMBER = 4;
    private java.lang.Object senderName_;
    /**
     * <code>required string senderName = 4;</code>
     */
    public boolean hasSenderName() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string senderName = 4;</code>
     */
    public java.lang.String getSenderName() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          senderName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string senderName = 4;</code>
     */
    public com.google.protobuf.ByteString
        getSenderNameBytes() {
      java.lang.Object ref = senderName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        senderName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VERSION_FIELD_NUMBER = 5;
    private int version_;
    /**
     * <code>required uint32 version = 5;</code>
     */
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required uint32 version = 5;</code>
     */
    public int getVersion() {
      return version_;
    }

    public static final int LIFECYCLESTATE_FIELD_NUMBER = 6;
    private int lifecycleState_;
    /**
     * <code>required uint32 lifecycleState = 6;</code>
     */
    public boolean hasLifecycleState() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 lifecycleState = 6;</code>
     */
    public int getLifecycleState() {
      return lifecycleState_;
    }

    public static final int ADDITIONALLIFECYCLEINFOS_FIELD_NUMBER = 7;
    private int additionalLifecycleInfos_;
    /**
     * <code>optional uint32 additionalLifecycleInfos = 7;</code>
     */
    public boolean hasAdditionalLifecycleInfos() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 additionalLifecycleInfos = 7;</code>
     */
    public int getAdditionalLifecycleInfos() {
      return additionalLifecycleInfos_;
    }

    public static final int ADDITIONALSTATEINFOS_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString additionalStateInfos_;
    /**
     * <code>optional bytes additionalStateInfos = 8;</code>
     */
    public boolean hasAdditionalStateInfos() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <code>optional bytes additionalStateInfos = 8;</code>
     */
    public com.google.protobuf.ByteString getAdditionalStateInfos() {
      return additionalStateInfos_;
    }

    public static final int MULTICASTIDENTIFIER_FIELD_NUMBER = 9;
    private int multicastIdentifier_;
    /**
     * <code>required uint32 multicastIdentifier = 9;</code>
     */
    public boolean hasMulticastIdentifier() {
      return ((bitField0_ & 0x00000100) == 0x00000100);
    }
    /**
     * <code>required uint32 multicastIdentifier = 9;</code>
     */
    public int getMulticastIdentifier() {
      return multicastIdentifier_;
    }

    private void initFields() {
      zmqPubPort_ = 0;
      zmqRepPort_ = 0;
      senderId_ = jmf.proto.FrameworkProto.SenderId.getDefaultInstance();
      senderName_ = "";
      version_ = 0;
      lifecycleState_ = 0;
      additionalLifecycleInfos_ = 0;
      additionalStateInfos_ = com.google.protobuf.ByteString.EMPTY;
      multicastIdentifier_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasZmqPubPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasZmqRepPort()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSenderName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVersion()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLifecycleState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMulticastIdentifier()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getSenderId().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, zmqPubPort_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, zmqRepPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, senderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSenderNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeUInt32(5, version_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, lifecycleState_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, additionalLifecycleInfos_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, additionalStateInfos_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        output.writeUInt32(9, multicastIdentifier_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, zmqPubPort_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, zmqRepPort_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, senderId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSenderNameBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, version_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, lifecycleState_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, additionalLifecycleInfos_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, additionalStateInfos_);
      }
      if (((bitField0_ & 0x00000100) == 0x00000100)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(9, multicastIdentifier_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static jmf.proto.FrameworkProto.StateBroadcast parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(jmf.proto.FrameworkProto.StateBroadcast prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code zmf.proto.StateBroadcast}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:zmf.proto.StateBroadcast)
        jmf.proto.FrameworkProto.StateBroadcastOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_StateBroadcast_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_StateBroadcast_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                jmf.proto.FrameworkProto.StateBroadcast.class, jmf.proto.FrameworkProto.StateBroadcast.Builder.class);
      }

      // Construct using jmf.proto.FrameworkProto.StateBroadcast.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSenderIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        zmqPubPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        zmqRepPort_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (senderIdBuilder_ == null) {
          senderId_ = jmf.proto.FrameworkProto.SenderId.getDefaultInstance();
        } else {
          senderIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        senderName_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        version_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        lifecycleState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        additionalLifecycleInfos_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        additionalStateInfos_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000080);
        multicastIdentifier_ = 0;
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return jmf.proto.FrameworkProto.internal_static_zmf_proto_StateBroadcast_descriptor;
      }

      public jmf.proto.FrameworkProto.StateBroadcast getDefaultInstanceForType() {
        return jmf.proto.FrameworkProto.StateBroadcast.getDefaultInstance();
      }

      public jmf.proto.FrameworkProto.StateBroadcast build() {
        jmf.proto.FrameworkProto.StateBroadcast result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public jmf.proto.FrameworkProto.StateBroadcast buildPartial() {
        jmf.proto.FrameworkProto.StateBroadcast result = new jmf.proto.FrameworkProto.StateBroadcast(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.zmqPubPort_ = zmqPubPort_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.zmqRepPort_ = zmqRepPort_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (senderIdBuilder_ == null) {
          result.senderId_ = senderId_;
        } else {
          result.senderId_ = senderIdBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.senderName_ = senderName_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.version_ = version_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.lifecycleState_ = lifecycleState_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.additionalLifecycleInfos_ = additionalLifecycleInfos_;
        if (((from_bitField0_ & 0x00000080) == 0x00000080)) {
          to_bitField0_ |= 0x00000080;
        }
        result.additionalStateInfos_ = additionalStateInfos_;
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000100;
        }
        result.multicastIdentifier_ = multicastIdentifier_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof jmf.proto.FrameworkProto.StateBroadcast) {
          return mergeFrom((jmf.proto.FrameworkProto.StateBroadcast)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(jmf.proto.FrameworkProto.StateBroadcast other) {
        if (other == jmf.proto.FrameworkProto.StateBroadcast.getDefaultInstance()) return this;
        if (other.hasZmqPubPort()) {
          setZmqPubPort(other.getZmqPubPort());
        }
        if (other.hasZmqRepPort()) {
          setZmqRepPort(other.getZmqRepPort());
        }
        if (other.hasSenderId()) {
          mergeSenderId(other.getSenderId());
        }
        if (other.hasSenderName()) {
          bitField0_ |= 0x00000008;
          senderName_ = other.senderName_;
          onChanged();
        }
        if (other.hasVersion()) {
          setVersion(other.getVersion());
        }
        if (other.hasLifecycleState()) {
          setLifecycleState(other.getLifecycleState());
        }
        if (other.hasAdditionalLifecycleInfos()) {
          setAdditionalLifecycleInfos(other.getAdditionalLifecycleInfos());
        }
        if (other.hasAdditionalStateInfos()) {
          setAdditionalStateInfos(other.getAdditionalStateInfos());
        }
        if (other.hasMulticastIdentifier()) {
          setMulticastIdentifier(other.getMulticastIdentifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasZmqPubPort()) {
          
          return false;
        }
        if (!hasZmqRepPort()) {
          
          return false;
        }
        if (!hasSenderId()) {
          
          return false;
        }
        if (!hasSenderName()) {
          
          return false;
        }
        if (!hasVersion()) {
          
          return false;
        }
        if (!hasLifecycleState()) {
          
          return false;
        }
        if (!hasMulticastIdentifier()) {
          
          return false;
        }
        if (!getSenderId().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        jmf.proto.FrameworkProto.StateBroadcast parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (jmf.proto.FrameworkProto.StateBroadcast) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int zmqPubPort_ ;
      /**
       * <code>required uint32 zmqPubPort = 1;</code>
       */
      public boolean hasZmqPubPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 zmqPubPort = 1;</code>
       */
      public int getZmqPubPort() {
        return zmqPubPort_;
      }
      /**
       * <code>required uint32 zmqPubPort = 1;</code>
       */
      public Builder setZmqPubPort(int value) {
        bitField0_ |= 0x00000001;
        zmqPubPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 zmqPubPort = 1;</code>
       */
      public Builder clearZmqPubPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        zmqPubPort_ = 0;
        onChanged();
        return this;
      }

      private int zmqRepPort_ ;
      /**
       * <code>required uint32 zmqRepPort = 2;</code>
       */
      public boolean hasZmqRepPort() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 zmqRepPort = 2;</code>
       */
      public int getZmqRepPort() {
        return zmqRepPort_;
      }
      /**
       * <code>required uint32 zmqRepPort = 2;</code>
       */
      public Builder setZmqRepPort(int value) {
        bitField0_ |= 0x00000002;
        zmqRepPort_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 zmqRepPort = 2;</code>
       */
      public Builder clearZmqRepPort() {
        bitField0_ = (bitField0_ & ~0x00000002);
        zmqRepPort_ = 0;
        onChanged();
        return this;
      }

      private jmf.proto.FrameworkProto.SenderId senderId_ = jmf.proto.FrameworkProto.SenderId.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          jmf.proto.FrameworkProto.SenderId, jmf.proto.FrameworkProto.SenderId.Builder, jmf.proto.FrameworkProto.SenderIdOrBuilder> senderIdBuilder_;
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public boolean hasSenderId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public jmf.proto.FrameworkProto.SenderId getSenderId() {
        if (senderIdBuilder_ == null) {
          return senderId_;
        } else {
          return senderIdBuilder_.getMessage();
        }
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public Builder setSenderId(jmf.proto.FrameworkProto.SenderId value) {
        if (senderIdBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          senderId_ = value;
          onChanged();
        } else {
          senderIdBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public Builder setSenderId(
          jmf.proto.FrameworkProto.SenderId.Builder builderForValue) {
        if (senderIdBuilder_ == null) {
          senderId_ = builderForValue.build();
          onChanged();
        } else {
          senderIdBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public Builder mergeSenderId(jmf.proto.FrameworkProto.SenderId value) {
        if (senderIdBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              senderId_ != jmf.proto.FrameworkProto.SenderId.getDefaultInstance()) {
            senderId_ =
              jmf.proto.FrameworkProto.SenderId.newBuilder(senderId_).mergeFrom(value).buildPartial();
          } else {
            senderId_ = value;
          }
          onChanged();
        } else {
          senderIdBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public Builder clearSenderId() {
        if (senderIdBuilder_ == null) {
          senderId_ = jmf.proto.FrameworkProto.SenderId.getDefaultInstance();
          onChanged();
        } else {
          senderIdBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public jmf.proto.FrameworkProto.SenderId.Builder getSenderIdBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getSenderIdFieldBuilder().getBuilder();
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      public jmf.proto.FrameworkProto.SenderIdOrBuilder getSenderIdOrBuilder() {
        if (senderIdBuilder_ != null) {
          return senderIdBuilder_.getMessageOrBuilder();
        } else {
          return senderId_;
        }
      }
      /**
       * <code>required .zmf.proto.SenderId senderId = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          jmf.proto.FrameworkProto.SenderId, jmf.proto.FrameworkProto.SenderId.Builder, jmf.proto.FrameworkProto.SenderIdOrBuilder> 
          getSenderIdFieldBuilder() {
        if (senderIdBuilder_ == null) {
          senderIdBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              jmf.proto.FrameworkProto.SenderId, jmf.proto.FrameworkProto.SenderId.Builder, jmf.proto.FrameworkProto.SenderIdOrBuilder>(
                  getSenderId(),
                  getParentForChildren(),
                  isClean());
          senderId_ = null;
        }
        return senderIdBuilder_;
      }

      private java.lang.Object senderName_ = "";
      /**
       * <code>required string senderName = 4;</code>
       */
      public boolean hasSenderName() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string senderName = 4;</code>
       */
      public java.lang.String getSenderName() {
        java.lang.Object ref = senderName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            senderName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string senderName = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSenderNameBytes() {
        java.lang.Object ref = senderName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          senderName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string senderName = 4;</code>
       */
      public Builder setSenderName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        senderName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string senderName = 4;</code>
       */
      public Builder clearSenderName() {
        bitField0_ = (bitField0_ & ~0x00000008);
        senderName_ = getDefaultInstance().getSenderName();
        onChanged();
        return this;
      }
      /**
       * <code>required string senderName = 4;</code>
       */
      public Builder setSenderNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        senderName_ = value;
        onChanged();
        return this;
      }

      private int version_ ;
      /**
       * <code>required uint32 version = 5;</code>
       */
      public boolean hasVersion() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required uint32 version = 5;</code>
       */
      public int getVersion() {
        return version_;
      }
      /**
       * <code>required uint32 version = 5;</code>
       */
      public Builder setVersion(int value) {
        bitField0_ |= 0x00000010;
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 version = 5;</code>
       */
      public Builder clearVersion() {
        bitField0_ = (bitField0_ & ~0x00000010);
        version_ = 0;
        onChanged();
        return this;
      }

      private int lifecycleState_ ;
      /**
       * <code>required uint32 lifecycleState = 6;</code>
       */
      public boolean hasLifecycleState() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 lifecycleState = 6;</code>
       */
      public int getLifecycleState() {
        return lifecycleState_;
      }
      /**
       * <code>required uint32 lifecycleState = 6;</code>
       */
      public Builder setLifecycleState(int value) {
        bitField0_ |= 0x00000020;
        lifecycleState_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 lifecycleState = 6;</code>
       */
      public Builder clearLifecycleState() {
        bitField0_ = (bitField0_ & ~0x00000020);
        lifecycleState_ = 0;
        onChanged();
        return this;
      }

      private int additionalLifecycleInfos_ ;
      /**
       * <code>optional uint32 additionalLifecycleInfos = 7;</code>
       */
      public boolean hasAdditionalLifecycleInfos() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional uint32 additionalLifecycleInfos = 7;</code>
       */
      public int getAdditionalLifecycleInfos() {
        return additionalLifecycleInfos_;
      }
      /**
       * <code>optional uint32 additionalLifecycleInfos = 7;</code>
       */
      public Builder setAdditionalLifecycleInfos(int value) {
        bitField0_ |= 0x00000040;
        additionalLifecycleInfos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 additionalLifecycleInfos = 7;</code>
       */
      public Builder clearAdditionalLifecycleInfos() {
        bitField0_ = (bitField0_ & ~0x00000040);
        additionalLifecycleInfos_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString additionalStateInfos_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes additionalStateInfos = 8;</code>
       */
      public boolean hasAdditionalStateInfos() {
        return ((bitField0_ & 0x00000080) == 0x00000080);
      }
      /**
       * <code>optional bytes additionalStateInfos = 8;</code>
       */
      public com.google.protobuf.ByteString getAdditionalStateInfos() {
        return additionalStateInfos_;
      }
      /**
       * <code>optional bytes additionalStateInfos = 8;</code>
       */
      public Builder setAdditionalStateInfos(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
        additionalStateInfos_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes additionalStateInfos = 8;</code>
       */
      public Builder clearAdditionalStateInfos() {
        bitField0_ = (bitField0_ & ~0x00000080);
        additionalStateInfos_ = getDefaultInstance().getAdditionalStateInfos();
        onChanged();
        return this;
      }

      private int multicastIdentifier_ ;
      /**
       * <code>required uint32 multicastIdentifier = 9;</code>
       */
      public boolean hasMulticastIdentifier() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>required uint32 multicastIdentifier = 9;</code>
       */
      public int getMulticastIdentifier() {
        return multicastIdentifier_;
      }
      /**
       * <code>required uint32 multicastIdentifier = 9;</code>
       */
      public Builder setMulticastIdentifier(int value) {
        bitField0_ |= 0x00000100;
        multicastIdentifier_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 multicastIdentifier = 9;</code>
       */
      public Builder clearMulticastIdentifier() {
        bitField0_ = (bitField0_ & ~0x00000100);
        multicastIdentifier_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:zmf.proto.StateBroadcast)
    }

    static {
      defaultInstance = new StateBroadcast(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:zmf.proto.StateBroadcast)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zmf_proto_SenderId_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zmf_proto_SenderId_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_zmf_proto_StateBroadcast_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_zmf_proto_StateBroadcast_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017Framework.proto\022\tzmf.proto\".\n\010SenderId" +
      "\022\016\n\006typeId\030\001 \002(\r\022\022\n\ninstanceId\030\002 \002(\004\"\371\001\n" +
      "\016StateBroadcast\022\022\n\nzmqPubPort\030\001 \002(\r\022\022\n\nz" +
      "mqRepPort\030\002 \002(\r\022%\n\010senderId\030\003 \002(\0132\023.zmf." +
      "proto.SenderId\022\022\n\nsenderName\030\004 \002(\t\022\017\n\007ve" +
      "rsion\030\005 \002(\r\022\026\n\016lifecycleState\030\006 \002(\r\022 \n\030a" +
      "dditionalLifecycleInfos\030\007 \001(\r\022\034\n\024additio" +
      "nalStateInfos\030\010 \001(\014\022\033\n\023multicastIdentifi" +
      "er\030\t \002(\rB\033\n\tjmf.protoB\016FrameworkProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_zmf_proto_SenderId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_zmf_proto_SenderId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zmf_proto_SenderId_descriptor,
        new java.lang.String[] { "TypeId", "InstanceId", });
    internal_static_zmf_proto_StateBroadcast_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_zmf_proto_StateBroadcast_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_zmf_proto_StateBroadcast_descriptor,
        new java.lang.String[] { "ZmqPubPort", "ZmqRepPort", "SenderId", "SenderName", "Version", "LifecycleState", "AdditionalLifecycleInfos", "AdditionalStateInfos", "MulticastIdentifier", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
